### ISSUE TITLE
Issue with Dockerfile.wn

### ISSUE THREAD

**Issue by faical-yannick-congo** [grycap/ec4docker#5]
For the line: docker build -f wn/Dockerfile.wn -t ec4docker:wn wn/
There is no file: wn/Dockerfile.wn but wn/Dockerfile.

**Comment by faical-yannick-congo** [comment]
I am one of your paper's reviewer for 'The Journal of Software and Systems'.

**Comment by amcaar** [comment]
Thank you for the comment. It was a mistake form previous versions of the code. Now, the Readme file is fixed.

**Comment by faical-yannick-congo** [comment]
Sure. Thanks.
